### ISSUE TITLE
Doesn't work with version 1.16.7 ?

### ISSUE THREAD

**Issue by Fred-DTV** [vavrecan/keeweb-local-server#9] opened 2021-01-07 14:16 UTC
I've just started using KeeWeb and this plugin, but it doesn't seem to work anymore?

**Comment by vavrecan** [comment] 2021-01-07 14:29
Hello,
I can confirm that latest version of keeweb is supported and quick installation script was updated.
https://github.com/vavrecan/keeweb-local-server/blob/master/install.sh
Thank you

**Comment by Fred-DTV** [comment] 2021-01-07 14:31
Ok i've tried the manual installation. I will try it again with the script. 

Sorry for bothering

**Comment by Fred-DTV** [comment] 2021-01-07 15:24
Unfortunately under win10 i only get ssh errors when trying to install it with wget.

I did a manual clean copy of both, your plugin and the keeweb's html but it still doesn't show up in the settings.
Any idea what could cause this?

**Comment by Fred-DTV** [comment] 2021-01-07 15:34
Really sorry for this. Finally i have it as an option but now i get this error:
![Screenshot 2021-01-07 at 16 33 31](https://user-images.githubusercontent.com/70434961/103911349-31ace480-5106-11eb-8b59-88e2bee6312a.jpg)

**Comment by vavrecan** [comment] 2021-01-07 15:54
Try browser inspector to see response from remote.php file

**Comment by Fred-DTV** [comment] 2021-01-07 16:10
This is the error i get:
2021-01-07T16:07:42.048Z [storage-localServerStorage] List error /server.php

I've tried these two settings:
```
// Path to kdbx databases
define("http://my.url/sub/databases");
define("BASE_PATH", __DIR__ . "/databases");
```


Oh and also this comes up:
`5[DOM] Password field is not contained in a form: (More info: <URL>) 
(index):1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" name=​"password">​
(index):1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"open__pass-input" name=​"password" type=​"password" size=​"30" autocomplete=​"new-password" maxlength=​"1024" placeholder=​"Click to open a file" readonly tabindex=​"23" aria-autocomplete=​"list">​
(index):1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) null
(index):1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" name=​"password">​
(index):1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"open__pass-input" name=​"password" type=​"password" size=​"30" autocomplete=​"new-password" maxlength=​"1024" placeholder=​"Click to open a file" readonly tabindex=​"23">​
`

**Comment by Fred-DTV** [comment] 2021-01-07 16:26
and finally this: `c8708f02-844e-4385-82b2-692a88d9ab57:212 GET https://dachsbau.club/server.php?path=. 404`

**Comment by vavrecan** [comment] 2021-01-07 18:18
it means server.php is missing. Upload server.php from this git repository https://github.com/vavrecan/keeweb-local-server/blob/master/server.php

**Comment by Fred-DTV** [comment] 2021-01-07 18:24
it is there though.


I've uploaded it again without editing it and it still has the issue

**Comment by vavrecan** [comment] 2021-01-07 18:39
download updated version of plugin 
https://github.com/vavrecan/keeweb-local-server
and update config.json with following
"localServerStorageScriptPath": "/keys/server.php"

it should then work even from subdirectory

**Comment by Fred-DTV** [comment] 2021-01-07 18:51
Thanks for your help! really appreciate it.

Unfortunately this doesn't work.
Whenever the setting is added it wont load the config.json anymore.

Tried to update and a full reinstall. Both times the site would only load without the setting in the json

**Comment by vavrecan** [comment] 2021-01-07 19:55
uh I see, make sure json syntax is correct

**Comment by Fred-DTV** [comment] 2021-01-07 20:42
Ok thanks you helped me come to a point where it's working now!
I had a "," too much in the config, what kept the page from loading, however, I could still access the list of databases.

Tried several password combinations (all of them would show authentication errors) and ended up trying it without a password at all. Then it worked.
The funny part is now: It works fine but I can't set a new password. It remembers that it used to be "passwordless" and stays in that state even when i enter a password in the server.php.

I will try another complete setup from scratch tomorrow to check if i can setup a password then.
But even if it stays like this that's fine for my usecase.

Thanks a lot Marek for your help. I will send you a tip for the hustle you went through with me.

**Comment by vavrecan** [comment] 2021-01-08 10:19
you are welcome, thank you as well as I could improve project too. It should be possible to set password in server.php script file, hopefully you will get it fully working

**Comment by Fred-DTV** [comment] 2021-01-08 16:10
Ok i couldn't make the password work yet, but i stumbled upon a new issue:
Changing the databases password doesn't seem to be possible. Have you tried this before?

**Comment by vavrecan** [comment] 2021-01-10 21:03
Changing Master Password should work, tested it locally. Try to clean up site data (ctrl + shit + i) - as the app is cached a lot.
![Screenshot from 2021-01-10 22-01-53](https://user-images.githubusercontent.com/1788049/104135291-a777b100-538f-11eb-9bd7-7d656cf3b6e2.png)

**Comment by Fred-DTV** [comment] 2021-01-21 15:32
Hey Marek,

So I've figured out why I can't change the password: The general syncing process doesn't work.
It also doesn't save any new entries to the database.
They are shown as long as the app is open, but as soon as I close it and load it again, the new entries are gone.

**Comment by vavrecan** [comment] 2021-01-21 18:16
Did you sync database after doing changes?

**Comment by Fred-DTV** [comment] 2021-01-21 18:18
The sync doesn't work. It will just stay in the sync state forever

**Comment by vavrecan** [comment] 2021-01-22 21:26
try checking web inspector and POST request to /server.php?save= ... 
does it throw any error? maybe database file is not writable on the server

**Comment by Fred-DTV** [comment] 2021-01-25 10:20
I can only see this error message:

`Uncaught TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.
    at LocalServerStorage._request (f2d5c40e-70ae-4fbf-94a6-b74f7fc9aa4d:204)
    at LocalServerStorage.stat (f2d5c40e-70ae-4fbf-94a6-b74f7fc9aa4d:54)
    at B.syncFile ((index):1)
    at (index):1`

**Comment by vavrecan** [comment] 2021-01-25 11:55
your server password probably contains a special character - non iso 8859
1. Because it is transferred over header it might be causing this error.
try changing server password

**Comment by Fred-DTV** [comment] 2021-01-25 13:35
It's weird, because i tried no password and "1234567890" and both times the error occurs

define("PASSWORD", "1234567890");
define("PASSWORD", "");

**Comment by vavrecan** [comment] 2021-01-25 14:16
Is it same error as before or different?
As this is hard to debug without having access to your host it might be the
best if you could do this on local server and write step by step how to
reproduce this issue

**Comment by Fred-DTV** [comment] 2021-01-29 17:01
Another day another chance :)

I've set it up new from scratch and the sync is working now. The only thing that still doesn't work is setting a password for the server. But I am happy with how it works now as my databases are saved with a password anyways

**Comment by Fred-DTV** [comment] 2021-01-30 12:06
damnit... again it is stuck in the sync loop forever.
the only error i see is again the sam as before:
![Screenshot 2021-01-30 at 13 04 43](https://user-images.githubusercontent.com/70434961/106355943-c49f0000-62fb-11eb-8b7f-1c2f1b5f855e.jpg)

I am not using a password for the server:
`// required password to write database
// leave empty to do not require password at all (not recommended)
// TODO change following option
define("PASSWORD", "");`

and my kdbx password only contains regular letters (A-Z) and a number and an exclamation mark

**Comment by vavrecan** [comment] 2021-03-02 18:47
Hopefully it all works for you, closing it for now. In case you have more problems even with latest version, we can start a new issue

**Closed as completed by vavrecan** 2021-03-02 18:47 UTC

**Comment by Fred-DTV** [comment] 2021-03-03 12:09
Hey hey, 
Unfortunately I couldn't make it work, so I had to switch to WebDAV.

But thanks for your effort anyways
